### ISSUE TITLE
All app enable or disable feature not working 

### ISSUE THREAD

**Issue by Abdullah3119** [aceventura82/AppsDisabler#10]
I am not able to enable or disable all apps in menu. I am able to enable or disable any app individualy by tapping on toggle from the list of apps. I am also able to enable any disabled app by tapping on its logo of it from menu. 
After tapping on All enable or All disable option in menu i get the toast "All apps Disabled/Enabled " but in real no change occoures ( also no colour changed of app name ) 

I have tried clearing data , reinstallation , grant root permission again 

I am using magisk 25.1 stable

**Comment by aceventura82** [comment]
Hello,
The option for enable All and disable all work with application you have selected for auto disable.

in the main apps view long tap to open the menu, then  Add App to auto disable

or in the setting apps list, tap in the app name (will select the hole row and activate both checks)
