### ISSUE TITLE
non-root situation

### ISSUE THREAD

**Issue by lostever** [aceventura82/AppsDisabler#2]
How to call shizuku's API so that the software becomes a device administrator in a non-root situation

**Comment by aceventura82** [comment]
Hello @lostever, Didn't know about that API, looks good
I'll check it out and try to implement it the App

Thanks

**Comment by aceventura82** [comment]
Hello @lostever, I have been checking the API but the documentation is not very good.
do you have any example of how to disable an app using this API
I manage to register the application with the shizuku app, but cannot find a way to run the disable command properly

**Comment by lostever** [comment]
Like this  
https://github.com/web1n/Stopapp-Docs

**Comment by lostever** [comment]
I konw nothing about android app .
I'm just wondering if it's going to work .
LOL

**Comment by aceventura82** [comment]
I will keep looking for a way for non ROOT phone, Sadly cannot find any documentation for shizuku's API 

Thanks!
