### ISSUE TITLE
Any magisk module req?

### ISSUE THREAD

**Issue by sudanking** [aceventura82/AppsDisabler#3]
Any Magisk module required to let that work smoothly?

**Comment by aceventura82** [comment]
Hi, no need any special module, just a rooted phone,  with Magisk or any root method

**Comment by sudanking** [comment]
Thanks to confirm that.

I like Disabler, it is promising... Try to open xda thread and telegram channel for your new app.. that will help to expand.

One more thing,plz consider it as upcoming/req feature, add gray icon at main launcher for frozen/disabled app. Also will be good if you share your roadmap.

Thanks for great job

**Comment by aceventura82** [comment]
Thanks for the advice.

I like the gray icon option, I hope will implementing it soon

**Comment by aceventura82** [comment]
Hello,

I have updated the app with the gray Icon Option

Also will put the XDA link in the GitHub Readme

https://forum.xda-developers.com/android/apps-games/app-disabler-app-to-easily-disable-app-t4121581
