### ISSUE TITLE
Back to homescreen.ver.1.18

### ISSUE THREAD

**Issue by GreenJunkie** [aceventura82/AppsDisabler#5]
If you tap outside the app, the app doesn't return to the app behind it, but instead returns to the home screen. The same goes for the back button. Previous versions reverted back to the app behind. Is this a specification?

**Comment by aceventura82** [comment]
Hi,

Yes that was intended for keeping the application running in the background for disabling apps when screen is Off
I was annoyed with this bug too, but haven't had time to check it up
But with a short search in Duckduckgo I Found out another way to go back without going home

So, I'm updating the app now to fix this annoying issue  
Will update to Version 1.19 later today

Thanks
