### ISSUE TITLE
No apps in app list in latest version

### ISSUE THREAD

**Issue by manuke42** [aceventura82/AppsDisabler#7]
hello. In the latest version (from F-Droid, 1.21) there are no apps listed in the app list and also not in the main screen. Before the update the app was working normally. I also get no toast message that superuser rights were used in latest version unlike before the update (may be related). Clearing app storage or reinstall didn't help either. I'm on Android 11.

**Comment by aceventura82** [comment]
Hello, looks like the applications has not root permission, can you double check in your root app that disabler has root permission

**Comment by manuke42** [comment]
I have reinstalled version 1.20 and there root permission is correctly asked for and i can grant it. But as soon as i install the latest 1.21 there is no granting dialog, no matter if i upgrade the app (so that the app stays in granted permission list of Magisk) or install freshly. Other root apps also work as expected.

**Comment by manuke42** [comment]
I just debugged and found the PackageManager in Android 11 just returns the system app information, then I found that in Android 11 you cannot query all packages installed without specific permission anymore:
https://proandroiddev.com/how-to-get-users-installed-apps-in-android-11-b4a4d2754286

you have to add the permission to the manifest:
`<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES"/>`

or solve it some other way. Hope it helps. When I add the permission to the manifest at least it works for me.

**Comment by aceventura82** [comment]
Hello,
II did added that permission previously in the last Version 1.21
can you please try with the last git version. looks like I have uploaded the wrong tag to f-droid
I have updated F-droid, but it will take 3-4 days to get public


https://github.com/aceventura82/AppsDisabler/blob/master/app/release/app-release.apk

Let me know if this version fix the problem

**Comment by manuke42** [comment]
Yes, indeed. It's in the code already :laughing: your linked version works. I will wait for F-Droid to push the update. Thanks for this app!

**Comment by aceventura82** [comment]
Thanks for notifying about this error!
Update will be Version 1.22
