### ISSUE TITLE
Disabler can't disable Instagram!

### ISSUE THREAD

**Issue by ruralTom** [aceventura82/AppsDisabler#9]
I removed it from the list and readded it. Turned on auto disable. used my widget to disable apps and the notification says 0 apps to disable. If I open Disabler, it's still in color....mocking me.

Can someone try testing this on their A11 device? I'm wanting to know if this is a bug, or a Tom problem first.

**Comment by aceventura82** [comment]
Have tried in Android 11, 12 and 12.1 and it's working as expected
Does it only happens with Instagram app? all other applications get disabled correctly?

**Comment by ruralTom** [comment]
Yes only with Instagram. 

Disregard, I removed and readded it and it functions as expected. The only thing I may have done different is I toggled both switches when adding it back.

**Comment by aceventura82** [comment]
that list view needs and update to make it clearer
There are 3 options there:
If you check  the "disable" check will only disable the application
If you check the "launcher" check, will show it in the app launcher
If you press the title will Disable the app, add it to the launcher and add it to the list of auto disable (with the disabler button, the widget or automatic when the elapsed time set)

**Comment by ruralTom** [comment]
Thank you for clearing that up

Jun 22, 2022 2:05:36 PM aceventura82 ***@***.***>:
